# Generated by Django 3.2.25 on 2025-11-27 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClickBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.BigIntegerField(help_text='关联的旅游景点 ID（Hive 数据源）')),
                ('scene', models.CharField(blank=True, help_text='触发场景，例如首页/搜索结果', max_length=32)),
                ('device', models.CharField(blank=True, help_text='客户端设备信息', max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exposure_id', models.CharField(blank=True, help_text='可选的曝光批次 ID，方便召回评估', max_length=64)),
            ],
            options={
                'verbose_name': '用户点击行为',
                'verbose_name_plural': '用户点击行为',
                'db_table': 'user_click_behavior',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='对外暴露的用户唯一 ID', unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('avatar', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.BigIntegerField(help_text='关联的旅游景点 ID（Hive 数据源）')),
                ('scene', models.CharField(blank=True, help_text='触发场景，例如首页/搜索结果', max_length=32)),
                ('device', models.CharField(blank=True, help_text='客户端设备信息', max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_favorite', models.BooleanField(default=True, help_text='True 表示收藏，False 表示取消')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavoritebehavior_records', to='user.userprofile')),
            ],
            options={
                'verbose_name': '用户收藏行为',
                'verbose_name_plural': '用户收藏行为',
                'db_table': 'user_favorite_behavior',
            },
        ),
        migrations.CreateModel(
            name='UserDetailViewBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.BigIntegerField(help_text='关联的旅游景点 ID（Hive 数据源）')),
                ('scene', models.CharField(blank=True, help_text='触发场景，例如首页/搜索结果', max_length=32)),
                ('device', models.CharField(blank=True, help_text='客户端设备信息', max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay_seconds', models.PositiveIntegerField(default=0, help_text='本次停留时长，单位秒')),
                ('from_click', models.ForeignKey(blank=True, help_text='如果详情来自某次点击，可关联点击记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_views', to='user.userclickbehavior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetailviewbehavior_records', to='user.userprofile')),
            ],
            options={
                'verbose_name': '用户查看详情行为',
                'verbose_name_plural': '用户查看详情行为',
                'db_table': 'user_detail_view_behavior',
            },
        ),
        migrations.CreateModel(
            name='UserCommentBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.BigIntegerField(help_text='关联的旅游景点 ID（Hive 数据源）')),
                ('scene', models.CharField(blank=True, help_text='触发场景，例如首页/搜索结果', max_length=32)),
                ('device', models.CharField(blank=True, help_text='客户端设备信息', max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='用户评分 0-5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True)),
                ('image_urls', models.TextField(blank=True, help_text='JSON 字符串形式存放评论配图 URL 列表，兼容 SQLite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercommentbehavior_records', to='user.userprofile')),
            ],
            options={
                'verbose_name': '用户评论行为',
                'verbose_name_plural': '用户评论行为',
                'db_table': 'user_comment_behavior',
            },
        ),
        migrations.AddField(
            model_name='userclickbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userclickbehavior_records', to='user.userprofile'),
        ),
    ]
